### ISSUE TITLE
Error when reading tfevents files written with TensorBoardLogger v0.1.21

### ISSUE THREAD

**Issue by BatyLeo** [PhilipVinc/TensorBoardLogger.jl#131] opened 2023-07-18 13:25 UTC
Hello, I updated `TensorboardLogger` to the latest `0.1.21` version, and the following minimum example doesn't work anymore:

```julia
using Logging
using TensorBoardLogger
using ValueHistories

logger = TBLogger("logs"; min_level=Logging.Info)

with_logger(logger) do
    @info "train" loss = 1.0
    @info "train" loss = 0.0
end

r = TBReader("logs1")
hist = MVHistory()

TensorBoardLogger.map_summaries(r) do tag, iter, val
    push!(hist, Symbol(tag), iter, val)
end
```

Here is the error:

```bash
ERROR: AssertionError: crc_data == crc_data_ck
Stacktrace:
 [1] read_event(f::IOStream)
   @ TensorBoardLogger ~/.julia/packages/TensorBoardLogger/LO5eP/src/Deserialization/deserialization.jl:49
 [2] iterate(it::TensorBoardLogger.TBEventFileIterator, state::Int64)
   @ TensorBoardLogger ~/.julia/packages/TensorBoardLogger/LO5eP/src/Deserialization/deserialization.jl:126
 [3] map_summaries(fun::var"#21#22", logdir::TBReader; purge::Bool, tags::Nothing, steps::Nothing, smart::Bool)
   @ TensorBoardLogger ~/.julia/packages/TensorBoardLogger/LO5eP/src/Deserialization/deserialization.jl:270
 [4] map_summaries(fun::Function, logdir::TBReader)
   @ TensorBoardLogger ~/.julia/packages/TensorBoardLogger/LO5eP/src/Deserialization/deserialization.jl:248
```

Reading files written with an older version still works.
Am I missing something ?

ps: by the way, it seems that version `0.1.20` cannot be installed from the general registry for some reason (only from the github repository url)

**Comment by JamieMair** [comment] 2023-07-19 13:31
I can confirm that I am having the same error. 

I have tracked down the commit which introduced this error (see https://github.com/JuliaLogging/TensorBoardLogger.jl/commit/45f831e21570870e11825f34b5b2aeeebc456f15). It is caused by upgrading to the a newer protobuf version. I would guess that the `masked_crc32c` ([this file](https://github.com/JuliaLogging/TensorBoardLogger.jl/blob/45f831e21570870e11825f34b5b2aeeebc456f15/src/utils.jl)) is perhaps faulty? I keep getting checksum errors for my own issues.

EDIT: MWE without other deps:
```julia
using Logging
using TensorBoardLogger

logger = TBLogger("logs", tb_increment)

with_logger(logger) do
    @info "train" loss = 1.0
    @info "train" loss = 0.0
end

r = TBReader("logs")

println("tag\titer\tval")
TensorBoardLogger.map_summaries(r) do tag, iter, val
    println("$tag\t$iter\t$val")
end
```

**Comment by JamieMair** [comment] 2023-07-21 09:37
@BatyLeo https://github.com/JuliaLogging/TensorBoardLogger.jl/pull/132 will fix hopefully fix the issue. If you would like to try out the fix before it is merged, you can checkout the branch
```julia
pkg> rm TensorBoardLogging
pkg> add https://github.com/JamieMair/TensorBoardLogger.jl#fix-serialisation-bug
```
Just be sure to switch back to the original package once the PR is merged.

**Comment by BatyLeo** [comment] 2023-07-21 11:50
I just tested the changes, and it seems to work. Thank you for the quick fix !

**Closed as completed** 2023-07-22 07:24 UTC
